/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_4 (
    input [15:0] a,
    input [15:0] b,
    input [1:0] alufnIn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] outread;
  
  always @* begin
    if (alufnIn == 2'h0) begin
      out = a + b;
      outread = a + b;
    end else begin
      if (alufnIn == 2'h1) begin
        out = a - b;
        outread = a - b;
      end else begin
        if (alufnIn == 2'h2) begin
          out = a * b;
          outread = a * b;
        end else begin
          if (alufnIn == 2'h3) begin
            out = a / b;
            outread = a / b;
          end else begin
            out = 1'h0;
            outread = 1'h0;
          end
        end
      end
    end
    n = outread[15+0-:1];
    v = (a[15+0-:1] & b[15+0-:1] & (~outread[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & outread[15+0-:1]);
    z = (~|outread);
  end
endmodule
