/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_6 (
    input [15:0] a,
    input [3:0] b,
    input [2:0] alufnIn,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] temp1;
  
  reg [15:0] temp2;
  
  always @* begin
    if (alufnIn == 3'h0) begin
      out = a << b;
    end else begin
      if (alufnIn == 3'h1) begin
        out = a >> b;
      end else begin
        if (alufnIn == 3'h3) begin
          out = $signed(a) >>> b;
        end else begin
          if (alufnIn == 3'h4) begin
            temp1 = a >> b;
            temp2 = a << (5'h10 - b);
            out = temp1 + temp2;
          end else begin
            if (alufnIn == 3'h5) begin
              temp1 = a << b;
              temp2 = a >> (5'h10 - b);
              out = temp1 + temp2;
            end else begin
              out = 1'h0;
            end
          end
        end
      end
    end
  end
endmodule
